// <auto-generated />
namespace MedRideCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedvalidationattributestocustomer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedvalidationattributestocustomer));
        
        string IMigrationMetadata.Id
        {
            get { return "201712052253344_Added validation attributes to customer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
