// <auto-generated />
namespace MedRideCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixtheabbreviatednamesofMinnesotaMississippiMissouriMontana : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixtheabbreviatednamesofMinnesotaMississippiMissouriMontana));
        
        string IMigrationMetadata.Id
        {
            get { return "201712072121397_Fix the abbreviated names of Minnesota, Mississippi, Missouri, Montana"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
