// <auto-generated />
namespace MedRideCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixissueofhavingmultiplestateswithabbreviatednameAK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixissueofhavingmultiplestateswithabbreviatednameAK));
        
        string IMigrationMetadata.Id
        {
            get { return "201712072139095_Fix issue of having multiple states with abbreviated name AK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
